using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyConfigurationAttribute("net-4.0.win32; release")]
[assembly: AssemblyProductAttribute("Quarz.NET 2.6.1 for .NET 4.0")]
[assembly: AssemblyDescriptionAttribute("Quartz Scheduling Framework for .NET")]
[assembly: AssemblyCopyrightAttribute("Copyright 2006-2017 Marko Lahma")]
[assembly: AssemblyTrademarkAttribute("Apache License, Version 2.0")]
[assembly: AssemblyCompanyAttribute("http://www.quartz-scheduler.net/")]
[assembly: AssemblyCultureAttribute("")]
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyVersionAttribute("2.6.1.0")]
[assembly: AssemblyInformationalVersionAttribute("2.6.1.221 / c2fa830f7615cca55813cec6d8cfd7e2ae085f90")]
[assembly: AssemblyDelaySignAttribute(false)]

